### ISSUE TITLE
Improve standardize_dataframe documentation

### ISSUE THREAD

**Issue by andim** [andim/pyrepseq#12]
The docstring could be improved by giving some indication of how the col_mapper object should be constructed

**Comment by yutanagano** [comment]
@andim happy to update the docs! But was unsure what exactly you had in mind- the docs already say that it should be a mapping object like a dictionary?

**Comment by yutanagano** [comment]
I just chatted to Sankalan about this issue and he said that maybe it would be good to add examples here. I will make time to do that.
