### ISSUE TITLE
Refactor nearest neighbor module

### ISSUE THREAD

**Issue by andim** [andim/pyrepseq#15]
A couple of refactoring suggestions:

- To help declutter the namespace it would be useful to make the helper functions in the nearest neighbor module private.
- The code in util.py which is currenlty only used in the nearest neighbor module should be merged into this module.
- The file name should be shortened to nn.
- The module should be imported to the main namespace.

**Comment by heartnetkung** [comment]
I've completed all the tasks. I'm sorry that I mistakenly pushed to the main branch.

1. To help declutter the namespace it would be useful to make the helper functions in the nearest neighbor module private.
  * it is done using underscore prefix as mentioned here https://stackoverflow.com/questions/551038/private-implementation-class-in-python
  * I also tested by printing all global variables to confirm the behavior
2. The code in util.py which is currenlty only used in the nearest neighbor module should be merged into this module.
  * I've moved all functions as you requested except for `ensure_numpy()` which is also used by James.
  * This function prevents common bugs of inputting pandas series and python list in place of a numpy list, so I anticipate that it can be used in other functions as well.
  * However, if you want me to remove it I can do that as well.
3.  The file name should be shortened to nn.
  * done
4. The module should be imported to the main namespace.
  * done

**Comment by andim** [comment]
Great! Thank you very much for turning this around so quickly. Adding an underscore to make the functions internal is exactly what I had in mind.
