### ISSUE TITLE
minor bug in tcrdist calculation

### ISSUE THREAD

**Issue by heartnetkung** [andim/pyrepseq#27]
TCRdist is Levenshtein distance which is [weighted and trimmed](https://github.com/agartland/pwseqdist/blob/852e159ad12582973bfbf23dd33fef068723742e/pwseqdist/nb_metrics.py#L117), however our current [implementation](https://github.com/andim/pyrepseq/blob/6e0ada263feffe06f99a8c92b32783b6cf87af20/pyrepseq/nn.py#L519) doesn't account for the trimming. I believe the correct implementation would need to trim the sequences before using nearest neighbor search. Without it, nearest neighbor search might miss some TCRdist-valid pairs.

**Comment by heartnetkung** [comment]
Oops, I misunderstand the function's intention. However, using trimmed version in Levenshtein calculation should speed up the calculation as well as retaining more valid pairs.

**Comment by andim** [comment]
Implemented in 7cc12f3 

Thanks!
